# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Week3_assignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Moya', '~> 15.0'
  # Pods for Week3_assignment

end
